apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- role.yaml
- rolebinding.yaml
- daemonset.yaml
