apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nri-resource-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nri-resource-policy
subjects:
- kind: ServiceAccount
  name: nri-resource-policy
  namespace: default
