apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

images:
- name: '*'
  newName: nri-resource-policy-topology-aware
  newTag: devel

resources:
- ../../base/crds
- ../../base/nri-resource-policy
- sample-configmap.yaml
