apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

images:
- name: '*'
  newName: nri-resmgr-balloons
  newTag: devel

resources:
- ../../base/crds
- ../../base/nri-resmgr
- sample-configmap.yaml
