#
# This example creates 3 ConfigMaps:
#  - nri-resmgr-config.default: the default configuration
#  - nri-resmgr-config.group.foo: the configuration for nodes in group foo
#  - nri-resmgr-config.node.cl0-slave1: the configuration for node cl0-slave1
#
# You can assign nodes to group foo using the command
#   kubectl label --overwrite node $NODE_NAME nri-resource-manager.intel.com/group=foo
#
# You can remove nodes from group foo using the command
#   kubectl label node $NODE_NAME nri-resource-manager.intel.com/group-
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-resmgr-config.default
  namespace: kube-system
data:
  policy: |+
    Active: topology-aware
    ReservedResources:
      cpu: 750m
    topology-aware:
      PinCPU: true
      PinMemory: true
      PreferIsolatedCPUs: true
      PreferSharedCPUs: false
